# Generated by Django 2.2 on 2020-08-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.CharField(max_length=500, verbose_name='Запись')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время  создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('blocked', 'Заблокировано')], default='active', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
