# Generated by Django 2.2 on 2020-08-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200801_0619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bock',
            new_name='GuestBook',
        ),
    ]
