# Generated by Django 2.2 on 2020-08-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200801_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
    ]
